version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/projects/ziti-console-lib"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
