name: Deploy Node ZAC Container

on:
  workflow_dispatch:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    if: startsWith(github.event.release.name, 'app-ziti-console-v')
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ vars.DOCKER_HUB_API_USER || secrets.DOCKER_HUB_API_USER }}
          password: ${{ secrets.DOCKER_HUB_API_TOKEN }}
      - name: Push to Docker
        env:
          ZAC_IMAGE_REPO: ${{ vars.ZAC_IMAGE_REPO || 'openziti/zac' }}
        run: ./pushLatestDocker.sh
